### ISSUE TITLE
Ask for lusc centroid data

### ISSUE THREAD

**Issue by lh12565** [pstew/proteogenomics_scc#1]
Hi, Could you provide the "data/main/wilkerson.scc/predictor.centroids.csv" for me. The url "http://cancer.unc.edu/nhayes/publications/scc/wilkerson.scc.tgz" in original article is not accessible.
Thanks!

**Comment by pstew** [comment]
I had actually emailed Wilkerson about this. He now has the signatures available here https://github.com/mwilkers/lungCancerSubtypes .

**Comment by lh12565** [comment]
> I had actually emailed Wilkerson about this. He now has the signatures available here https://github.com/mwilkers/lungCancerSubtypes .

Thanks! Could you provide the subtype (primitive	classical	secretory	basal) of each TCGA LUSC sample in "Comprehensive genomic characterization of squamous cell lung cancers".
